### ISSUE TITLE
"Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by mfirry** [brainshave/ancient-oak#14]
I constantly get 
node_modules/ancient-oak/lib/balanced_storage/storage.js:48
    var set = modifier({
    ^
RangeError: Maximum call stack size exceeded

when trying to use ancient-oak on something like this: http://hastebin.com/uxeneconom.dos

**Comment by szymonrw** [comment]
Hi @mfirry. For a long time I had my GH notifications disabled and I missed this one. Apologies.

The link to the hastebin doesn't work. Any chance you still have the code hanging around? I'd be happy to help if you still have the example data that caused this error.

**Comment by mfirry** [comment]
Oh man... that's a long time ago! I'll try find out what the heck I was trying to do and let you know.
Thanks anyway.

**Comment by mfirry** [comment]
Closing this ok @brainshave?
